### ISSUE TITLE
FYI: Code you might find useful

### ISSUE THREAD

**Issue by alphapapa** [zellerin/dynamic-graphs#2]
Hi,

I just saw your package, which looks very interesting.  It's similar in some ways to a package I haven't officially published yet, https://github.com/alphapapa/org-graph-view.  You might find some of the GraphViz-related code useful, e.g. [this function](https://github.com/alphapapa/org-graph-view/blob/13314338d70d2c19511efccc491bed3ca0758170/org-graph-view.el#L482), or the code that uses hrefs to make nodes clickable without saving a separate map file.

**Comment by zellerin** [comment]
Hi,

thanks,  there seems to be some overlaps :) 

I might use the code to generate file-less images and maps if you don't mind, even though I would want to keep the current option available (I consider starting with preexisting image and imap file as a use case). I did not make your package work on my machine (I do not see starting instructions, simple org-map-view in org mode caused an error, and function from gif did not exist)

Otherwise, I think we do not overlap much - I intentionally deleted all references to org-to-graphviz code from my package (yes, it originated as clickable org indexer as well), as this is covered on many other places (and it starts with sly-eval and core is in common lisp, so not much shareable - but it handles links, as I can see suggested in one of issues at your package). And one of my primary goals is "styling" with gvpr, while you generate target graphviz code immediately.

**Comment by zellerin** [comment]
New master uses cmapx format by default, and creates images and maps without use of external files.

Thanks for inspiration.
